apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-duel-client
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: snake.raphcvr.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake-duel-client
                port:
                  name: http
