apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - behavior: replace
    name: snake-duel-client-config
    envs:
      - client-config.env

images:
  - name: snake-duel-client
    newName: ghcr.io/raphcvr/snakebattleroyal-client
    newTag: latest
  - name: snake-duel-server
    newName: ghcr.io/raphcvr/snakebattleroyal-server
    newTag: latest

patches:
  - path: client-ingress-patch.yaml
  - path: server-ingress-patch.yaml
